WAIT UNTIL ETA:APOAPSIS < 5.

SET direction TO RETROGRADE.
LOCK STEERING TO direction.
LOCK THROTTLE TO 1.

WAIT UNTIL PERIAPSIS < 55000.
LOCK THROTTLE TO 0.
LOCK STEERING TO RETROGRADE.

WAIT UNTIL ETA:PERIAPSIS < 5.
LOCK THROTTLE TO 1.

WAIT UNTIL ALT:RADAR < 25000.

STAGE.
