// Rescuer Deorbit v1.0.0
// Kevin Gisi
// http://youtube.com/gisikw

// Deorbit
TOGGLE LIGHTS.
LOCK STEERING TO RETROGRADE.
WAIT 10.
LOCK THROTTLE TO 1.
WAIT UNTIL STAGE:LIQUIDFUEL < 1. WAIT 1.
STAGE. WAIT 1. STAGE.

// Handle descent
LOCK STEERING TO SRFRETROGRADE.
WAIT UNTIL ALT:RADAR < 500.
UNLOCK STEERING.
